version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/smart360/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 600
      runas: root    
  BeforeInstall:
    - location: scripts/install_application
      timeout: 600
      runas: root
    - location: scripts/remove_files
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 600
      runas: root