  
version: 0.2

phases:

  build:
  
    command:
    -echo "this is build phase..... zipping my webpage"

      
  post_build:
    commands:
      - echo "Depolyed to S3"

artifacts:
    files:
        - '**/*'
    discard-paths: no
