  
version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.7
    commands:
      #- "yum update -y"
      - echo Installing dependencies


  pre_build:
    commands:
      - pip install -r requirement.txt
      
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
    files:
        - '**/*'
    discard-paths: no
