  
version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - pip install -r blog/requirement.txt
      
  post_build:
    commands:
      - echo "Depolyed to S3"

artifacts:
    files:
        - '**/*'
    discard-paths: no
