#!/bin/bash

sudo systemctl start gunicorn.socket gunicorn.service
sudo systemctl enable gunicorn.socket
sudo systemctl status gunicorn.socket
sudo journalctl -u gunicorn.socket
sudo systemctl daemon-reload
sudo systemctl restart gunicorn
sudo systemctl restart nginx